
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/database.types';

const SUPABASE_URL = "https://svenmlcxebqafsxlayez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2ZW5tbGN4ZWJxYWZzeGxheWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzM3MTksImV4cCI6MjA1OTEwOTcxOX0.VhswszCSvkZXMXZf9yIbCmwMkbhjpE156iMq5XaCUoM";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
